#ifndef LITE3_DYNAMICS__DYNAMICS_HPP_
#define LITE3_DYNAMICS__DYNAMICS_HPP_

#include <Eigen/Dense>
#include <lite3_kinematics/kinematics.hpp>

namespace lite3_dynamics
{

enum class Link
{
  HIPX = 0,
  HIPY = 1,
  KNEE = 2,
  FOOT = 3
};

struct LinkMassProperty
{
  double mass;

  // COM expressed in the corresponding link frame.
  Eigen::Vector3d com;

  // Inertia about COM, expressed in the link frame.
  Eigen::Matrix3d inertia;
};

struct LegMassProperties
{
  LinkMassProperty hipx;
  LinkMassProperty hipy;
  LinkMassProperty knee;
  LinkMassProperty foot;
};

struct LegGeometry
{
  double hip_x;
  double hip_y;
  double hip_y_offset;
  double thigh_length;
  double shank_length;
};

class Lite3SingleLegDynamics
{
public:

  Lite3SingleLegDynamics();

  Eigen::Vector3d centerOfMass(
    lite3_kinematics::Leg leg,
    Link link,
    const Eigen::Vector3d &q) const;

  double potentialEnergy(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  Eigen::Vector3d gravityTorque(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  /**
   * @brief Joint-space mass matrix M(q).
   */
  Eigen::Matrix3d massMatrix(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  /**
   * @brief Kinetic energy using T = 1/2 qdot^T M qdot.
   */
  double kineticEnergy(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q,
    const Eigen::Vector3d &qdot) const;

  Eigen::Vector3d torqueMassGravity(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q,
  const Eigen::Vector3d &qddot) const;

  /**
 * @brief Coriolis/centrifugal matrix C(q,qdot).
 */
Eigen::Matrix3d coriolisMatrix(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q,
  const Eigen::Vector3d &qdot) const;

/**
 * @brief Coriolis and centrifugal generalized torque.
 */
Eigen::Vector3d coriolisTorque(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q,
  const Eigen::Vector3d &qdot) const;

/**
 * @brief Complete inverse dynamics torque.
 *
 * tau = M(q) qddot + C(q,qdot) qdot + G(q)
 */
Eigen::Vector3d inverseDynamics(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q,
  const Eigen::Vector3d &qdot,
  const Eigen::Vector3d &qddot) const;

/**
 * @brief Position Jacobian of the foot.
 *
 * J maps joint velocity to foot linear velocity:
 *
 * v_foot = J_foot qdot
 */
Eigen::Matrix3d footJacobian(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q) const;

/**
 * @brief Joint torque generated by an external foot force.
 *
 * tau_contact = J_foot^T F_contact
 */
Eigen::Vector3d contactTorque(
  lite3_kinematics::Leg leg,
  const Eigen::Vector3d &q,
  const Eigen::Vector3d &force) const;

private:

  LegMassProperties getMassProperties(
    lite3_kinematics::Leg leg) const;

  LegGeometry getGeometry(
    lite3_kinematics::Leg leg) const;

  Eigen::Isometry3d hipXTransform(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  Eigen::Isometry3d hipYTransform(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  Eigen::Isometry3d kneeTransform(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;

  Eigen::Isometry3d footTransform(
    lite3_kinematics::Leg leg,
    const Eigen::Vector3d &q) const;
};

}  // namespace lite3_dynamics

#endif