<?xml version="1.0"?>
<package format="3">

    <name>lite3_description</name>
    <version>0.0.1</version>

    <description>
        For description and robot model of the DeepRobotics Lite3 quadruped robot
    </description>

    <maintainer email="senaalfarabi31@gmail.com">Lexion</maintainer>

    <license>Apache-2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <exec_depend>robot_state_publisher</exec_depend>
    <exec_depend>joint_state_publisher</exec_depend>
    <exec_depend>rviz2</exec_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>

</package>